/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appabsensismpihidayatuttholibin.view;

import appabsensismpihidayatuttholibin.Config.Koneksi;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class formLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formLogin.class.getName());

    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
        
        borderLengkung(pnlpassword, "#FFFFFF");
    }
    
    void borderLengkung(JPanel panel, String hexColor) {
        panel.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0),
                Color.decode(hexColor),
                1f,
                20
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tUsername = new javax.swing.JTextField();
        bLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlpassword = new javax.swing.JPanel();
        tPassword = new javax.swing.JPasswordField();
        btnMata = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 250, 253));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1632, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(246, 250, 253));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(246, 250, 253));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1632, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(246, 250, 253));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(246, 250, 253));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(246, 250, 253));
        jPanel6.setPreferredSize(new java.awt.Dimension(715, 700));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/Frame 9 (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(201, 223, 237));
        jPanel8.setPreferredSize(new java.awt.Dimension(650, 700));

        tUsername.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        tUsername.setText("Masukkan Username");
        tUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tUsernameFocusLost(evt);
            }
        });

        bLogin.setBackground(new java.awt.Color(39, 81, 103));
        bLogin.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setText("Login");
        bLogin.addActionListener(this::bLoginActionPerformed);

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        jLabel2.setText("Login");

        pnlpassword.setBackground(new java.awt.Color(255, 255, 255));
        pnlpassword.setLayout(new java.awt.GridBagLayout());

        tPassword.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        tPassword.setText("Masukkan Password");
        tPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPasswordFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 365;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlpassword.add(tPassword, gridBagConstraints);

        btnMata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/icons8-hide-20.png"))); // NOI18N
        btnMata.setOpaque(true);
        btnMata.setPreferredSize(new java.awt.Dimension(27, 27));
        btnMata.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/icons8-eye-20.png"))); // NOI18N
        btnMata.addActionListener(this::btnMataActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlpassword.add(btnMata, gridBagConstraints);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(bLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel2)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        //Ambil teks yang dimasukkan user pada field username
        String username = tUsername.getText();
        
        //Ambil teks yang dimasukkan user pada field password
        String password = tPassword.getText();
        
        //periksa apakah username dan password tidak kosong
        if (username.length() != 0 && password.length() != 0){
            try {
                //Query SQL untuk mencari user dengan username dan password (dihash dengan MDS)
                String sql = "SELECT * FROM pengguna WHERE nama_pengguna=? AND password=md5(?)";

                //Buat koneksi ke database
                Connection con = Koneksi.konek();

                //siapkan statement SQL dengan parameter
                PreparedStatement ps = con.prepareStatement(sql);

                //isi parameter pertama (?) dengan username
                ps.setString(1, username);

                //isi parameter kedua (?) dengan password yang akan dihash MD5 di sisi database
                ps.setString(2, password);

                //jalankan query dan ambil hasilnya
                ResultSet rs = ps.executeQuery();

                //jika hasil query memiliki baris (berarti login berhasil)
                if (rs.next()) {
                    //role
                    String role = rs.getString("role");
                    
                    //buka form Dashboard
                    new mainForm().setVisible(true);
                    
                    //tutup form login
                    dispose();
                    
                } else {
                    //jika data tidak ditemukan, tampilkan pesan error
                    JOptionPane.showMessageDialog(null, "Username/password salah");
                }
            } catch (SQLException sQLException) {
                //jika terjadi kesalahan SQL, tampilkan pesan error
                JOptionPane.showMessageDialog(null, sQLException.getMessage());
            } 
        }else {
            //jika usename atau password kosong, beri peringatan ke user
            JOptionPane.showMessageDialog(null, "Username/password tidak boleh kosong");
        }
    }//GEN-LAST:event_bLoginActionPerformed

    //Memberi fokus gained agar tulisan di text field kosong saat di klik
    private void tUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusGained
        // TODO add your handling code here:
        String Username = tUsername.getText();
        if(Username.equals("Masukkan Username")){
            tUsername.setText("");
        }
    }//GEN-LAST:event_tUsernameFocusGained

    
    //Memberi fokus lost agar tulisan di text field kosong saat di klik
    //dan kembali lagi jika tidak jadi dinputkan
    private void tUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusLost
        // TODO add your handling code here:
        String Username = tUsername.getText();
        if(Username.equals("")||Username.equals("Masukkan Username")){
            tUsername.setText("Masukkan Username");
        }
    }//GEN-LAST:event_tUsernameFocusLost

    private void tPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPasswordFocusGained
        // TODO add your handling code here:
        String password = tPassword.getText();
        if(password.equals("Masukkan Password")){
            tPassword.setText("");
        }
    }//GEN-LAST:event_tPasswordFocusGained

    private void btnMataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMataActionPerformed
        // TODO add your handling code here:
        if (btnMata.isSelected()){
            //password terlihat
            tPassword.setEchoChar((char)0);
        }else {
            //password disembunyikan
            tPassword.setEchoChar('.');
        }
    }//GEN-LAST:event_btnMataActionPerformed

    private void tPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPasswordFocusLost
        // TODO add your handling code here:
        String password = tPassword.getText();
        if(password.equals("")||password.equals("Masukkan Password")){
            tPassword.setText("Masukkan Password");
        }
    }//GEN-LAST:event_tPasswordFocusLost

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.arc", 20);
            UIManager.put("Button.borderwidht", 0);
            UIManager.put("TextComponent.arc", 20);
            UIManager.put("Component.borderwidht", 0);
            UIManager.put("Component.focusWidth", 0);
            UIManager.put("Component.innerFocuswidht", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JToggleButton btnMata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel pnlpassword;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
