/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appabsensismpihidayatuttholibin.view;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import appabsensismpihidayatuttholibin.view.mainPanel.panelDashboard;
import appabsensismpihidayatuttholibin.view.mainPanel.panelGuru;
import appabsensismpihidayatuttholibin.view.mainPanel.panelKelas;
import appabsensismpihidayatuttholibin.view.mainPanel.panelSiswa;
import appabsensismpihidayatuttholibin.view.mainPanel.panelGenerateQR;
import appabsensismpihidayatuttholibin.view.mainPanel.panelPengguna;
import appabsensismpihidayatuttholibin.view.mainPanel.panelPergantianGuru;
import appabsensismpihidayatuttholibin.view.mainPanel.panelAbsensiQR;
import appabsensismpihidayatuttholibin.view.mainPanel.panelAbsensiManual;
import appabsensismpihidayatuttholibin.view.mainPanel.panelLaporan;
import appabsensismpihidayatuttholibin.view.mainPanel.panelAbout;
import java.awt.CardLayout;

/**
 *
 * @author ASUS
 */
public class mainForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainForm.class.getName());
    private CardLayout cardLayout;
    /**
     * Creates new form mainForm
     */    
    public mainForm() {
        initComponents();
        
        //memanggil method panel 
        inisiasiPanel();
        
        //memanggil method untuk tanggal dan jam
        tanggaljam();
    }
    
    // method untuk memanggil main panel menggunakan cardlayout
    void inisiasiPanel(){
        cardLayout = (CardLayout)panelPerpindahan.getLayout();
        
        panelPerpindahan.add(new panelDashboard(), "dashboard");
        panelPerpindahan.add(new panelGuru(), "guru");
        panelPerpindahan.add(new panelKelas(), "kelas");
        panelPerpindahan.add(new panelSiswa(), "siswa");
        panelPerpindahan.add(new panelGenerateQR(), "generate");
        panelPerpindahan.add(new panelPengguna(), "pengguna");
        panelPerpindahan.add(new panelPergantianGuru(), "PG");
        panelPerpindahan.add(new panelAbsensiQR(), "QR");
        panelPerpindahan.add(new panelAbsensiManual(), "manual");
        panelPerpindahan.add(new panelLaporan(), "laporan");
        panelPerpindahan.add(new panelAbout(), "about");
    }
    
    // method untuk menampilkan tanggal dan jam
    void tanggaljam(){
        javax.swing.Timer timer = new javax.swing.Timer(1000, (java.awt.event.ActionEvent e) -> {
            java.util.Locale localeIndonesia = new java.util.Locale("id", "ID");
            
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(
                    "EEEE, dd MMMM yyyy | HH.mm",
                    localeIndonesia
            );
            
            String waktu = sdf.format(new java.util.Date());
            lTanggalJam.setText(waktu);
        });
        
        timer.start();
    }
    
    // membuat method bersih untuk tcari yang apabila diklik tulisan cari akan hilang
    void bersih(){
        tCari.setText("Cari");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bDashboard = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bGenerate = new javax.swing.JButton();
        bPengguna = new javax.swing.JButton();
        bPG = new javax.swing.JButton();
        bQR = new javax.swing.JButton();
        bManual = new javax.swing.JButton();
        bLaporan = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelTengah = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        LMenu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tCari = new javax.swing.JTextField();
        panelBottom = new javax.swing.JPanel();
        lTanggalJam = new javax.swing.JLabel();
        panelPerpindahan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(39, 81, 103));
        panelSidebar.setPreferredSize(new java.awt.Dimension(270, 900));

        jPanel3.setBackground(new java.awt.Color(39, 81, 103));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        bDashboard.setBackground(new java.awt.Color(39, 81, 103));
        bDashboard.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ph_chalkboard-teacher-duotone (5).png"))); // NOI18N
        bDashboard.setText("Dashboard");
        bDashboard.setBorderPainted(false);
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bDashboard.setIconTextGap(7);
        bDashboard.addActionListener(this::bDashboardActionPerformed);
        jPanel3.add(bDashboard);

        bGuru.setBackground(new java.awt.Color(39, 81, 103));
        bGuru.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/streamline-plump_class-lesson-remix (2).png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setBorderPainted(false);
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bGuru.addActionListener(this::bGuruActionPerformed);
        jPanel3.add(bGuru);

        bKelas.setBackground(new java.awt.Color(39, 81, 103));
        bKelas.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/streamline-plump_class-lesson-remix (2).png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setBorderPainted(false);
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bKelas.addActionListener(this::bKelasActionPerformed);
        jPanel3.add(bKelas);

        bSiswa.setBackground(new java.awt.Color(39, 81, 103));
        bSiswa.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ph_student-bold (2).png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setBorderPainted(false);
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bSiswa.addActionListener(this::bSiswaActionPerformed);
        jPanel3.add(bSiswa);

        bGenerate.setBackground(new java.awt.Color(39, 81, 103));
        bGenerate.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bGenerate.setForeground(new java.awt.Color(255, 255, 255));
        bGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/boxicons_qr-filled (2).png"))); // NOI18N
        bGenerate.setText("Generate QR");
        bGenerate.setBorderPainted(false);
        bGenerate.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bGenerate.addActionListener(this::bGenerateActionPerformed);
        jPanel3.add(bGenerate);

        bPengguna.setBackground(new java.awt.Color(39, 81, 103));
        bPengguna.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bPengguna.setForeground(new java.awt.Color(255, 255, 255));
        bPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/lsicon_report-outline (2).png"))); // NOI18N
        bPengguna.setText("Pengguna");
        bPengguna.setBorderPainted(false);
        bPengguna.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bPengguna.addActionListener(this::bPenggunaActionPerformed);
        jPanel3.add(bPengguna);

        bPG.setBackground(new java.awt.Color(39, 81, 103));
        bPG.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bPG.setForeground(new java.awt.Color(255, 255, 255));
        bPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ic_twotone-co-present (2).png"))); // NOI18N
        bPG.setText("Pergantian Guru");
        bPG.setBorderPainted(false);
        bPG.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bPG.addActionListener(this::bPGActionPerformed);
        jPanel3.add(bPG);

        bQR.setBackground(new java.awt.Color(39, 81, 103));
        bQR.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bQR.setForeground(new java.awt.Color(255, 255, 255));
        bQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/boxicons_qr-scan (2).png"))); // NOI18N
        bQR.setText("Absensi QR");
        bQR.setBorderPainted(false);
        bQR.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bQR.addActionListener(this::bQRActionPerformed);
        jPanel3.add(bQR);

        bManual.setBackground(new java.awt.Color(39, 81, 103));
        bManual.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bManual.setForeground(new java.awt.Color(255, 255, 255));
        bManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ic_twotone-class (2).png"))); // NOI18N
        bManual.setText("Abensi Manual");
        bManual.setBorderPainted(false);
        bManual.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bManual.addActionListener(this::bManualActionPerformed);
        jPanel3.add(bManual);

        bLaporan.setBackground(new java.awt.Color(39, 81, 103));
        bLaporan.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bLaporan.setForeground(new java.awt.Color(255, 255, 255));
        bLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/lsicon_management-outline (2).png"))); // NOI18N
        bLaporan.setText("Laporan");
        bLaporan.setBorderPainted(false);
        bLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bLaporan.addActionListener(this::bLaporanActionPerformed);
        jPanel3.add(bLaporan);

        bAbout.setBackground(new java.awt.Color(39, 81, 103));
        bAbout.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ix_about (2).png"))); // NOI18N
        bAbout.setText("About");
        bAbout.setBorderPainted(false);
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bAbout.addActionListener(this::bAboutActionPerformed);
        jPanel3.add(bAbout);

        bKeluar.setBackground(new java.awt.Color(39, 81, 103));
        bKeluar.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/humbleicons_logout (2).png"))); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.setBorderPainted(false);
        bKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bKeluar.addActionListener(this::bKeluarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 236, 236));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama Pengguna");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 236, 236));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appabsensismpihidayatuttholibin/Icon/ix_user-profile (1).png"))); // NOI18N

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addContainerGap(1364, Short.MAX_VALUE)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelTengah.setBackground(new java.awt.Color(201, 223, 237));
        panelTengah.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(246, 250, 253));
        Header.setPreferredSize(new java.awt.Dimension(1300, 70));
        Header.setLayout(new java.awt.BorderLayout());

        LMenu.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        LMenu.setText("     Nama Menu");
        LMenu.setAlignmentX(0.5F);
        LMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LMenu.setInheritsPopupMenu(false);
        LMenu.setPreferredSize(new java.awt.Dimension(300, 16));
        Header.add(LMenu, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(246, 250, 253));

        jPanel2.setBackground(new java.awt.Color(246, 250, 253));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tCari.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        tCari.setText("Cari");
        tCari.setPreferredSize(new java.awt.Dimension(71, 18));
        tCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCariFocusLost(evt);
            }
        });
        jPanel2.add(tCari, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1016, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Header.add(jPanel1, java.awt.BorderLayout.CENTER);

        panelTengah.add(Header, java.awt.BorderLayout.PAGE_START);

        panelBottom.setBackground(new java.awt.Color(246, 250, 253));
        panelBottom.setPreferredSize(new java.awt.Dimension(1330, 50));

        lTanggalJam.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lTanggalJam.setText("Day, dd Month yyyy | 00:00");

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBottomLayout.createSequentialGroup()
                .addContainerGap(1386, Short.MAX_VALUE)
                .addComponent(lTanggalJam, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTanggalJam, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTengah.add(panelBottom, java.awt.BorderLayout.PAGE_END);

        panelPerpindahan.setBackground(new java.awt.Color(201, 223, 237));
        panelPerpindahan.setLayout(new java.awt.CardLayout());
        panelTengah.add(panelPerpindahan, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "dashboard");
    }//GEN-LAST:event_bDashboardActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "guru");
    }//GEN-LAST:event_bGuruActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "kelas");
    }//GEN-LAST:event_bKelasActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "siswa");
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerateActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "generate");
    }//GEN-LAST:event_bGenerateActionPerformed

    private void bPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPenggunaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "pengguna");
    }//GEN-LAST:event_bPenggunaActionPerformed

    private void bPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPGActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "PG");
    }//GEN-LAST:event_bPGActionPerformed

    private void bQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQRActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "QR");
    }//GEN-LAST:event_bQRActionPerformed

    private void bManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManualActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "manual");
    }//GEN-LAST:event_bManualActionPerformed

    private void bLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "laporan");
    }//GEN-LAST:event_bLaporanActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelPerpindahan, "about");
    }//GEN-LAST:event_bAboutActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    
    
    private void tCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCariFocusGained
        // TODO add your handling code here:
        String Cari = tCari.getText();
        if(Cari.equals("Cari")){
            tCari.setText("");
        }
    }//GEN-LAST:event_tCariFocusGained

    private void tCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCariFocusLost
        // TODO add your handling code here:
        String Cari = tCari.getText();
        if(Cari.equals("")||Cari.equals("Cari")){
            tCari.setText("Cari");
        }
    }//GEN-LAST:event_tCariFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.arc", 20);
            UIManager.put("Button.borderwidht", 0);
            UIManager.put("TextComponent.arc", 20);
            UIManager.put("Component.borderwidht", 0);
            UIManager.put("Component.focusWidth", 0);
            UIManager.put("Component.innerFocuswidht", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LMenu;
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bGenerate;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bLaporan;
    private javax.swing.JButton bManual;
    private javax.swing.JButton bPG;
    private javax.swing.JButton bPengguna;
    private javax.swing.JButton bQR;
    private javax.swing.JButton bSiswa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lTanggalJam;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelPerpindahan;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelTengah;
    private javax.swing.JTextField tCari;
    // End of variables declaration//GEN-END:variables
}
